import { DashboardData } from './types'

export const mockDashboardData: DashboardData = {
  metrics: [
    {
      title: 'Total Revenue',
      value: '$124,352',
      change: '+12.5%',
      trend: 'up',
      icon: 'revenue',
    },
    {
      title: 'Active Users',
      value: '48,592',
      change: '+8.2%',
      trend: 'up',
      icon: 'users',
    },
    {
      title: 'Conversion Rate',
      value: '3.42%',
      change: '+0.18%',
      trend: 'up',
      icon: 'conversions',
    },
    {
      title: 'Growth Rate',
      value: '24.8%',
      change: '+2.1%',
      trend: 'up',
      icon: 'growth',
    },
  ],
  charts: {
    revenue: [
      { month: 'Jan', value: 4000 },
      { month: 'Feb', value: 3000 },
      { month: 'Mar', value: 5000 },
      { month: 'Apr', value: 4500 },
      { month: 'May', value: 6000 },
      { month: 'Jun', value: 5500 },
      { month: 'Jul', value: 7000 },
      { month: 'Aug', value: 6500 },
      { month: 'Sep', value: 8000 },
      { month: 'Oct', value: 7500 },
      { month: 'Nov', value: 9000 },
      { month: 'Dec', value: 8500 },
    ],
    campaigns: [
      { name: 'Google Ads', value: 4500 },
      { name: 'Facebook', value: 3200 },
      { name: 'Instagram', value: 2800 },
      { name: 'LinkedIn', value: 1900 },
      { name: 'Twitter', value: 1200 },
    ],
    traffic: [
      { name: 'Organic Search', value: 35, color: '#8B5CF6' },
      { name: 'Direct', value: 25, color: '#06B6D4' },
      { name: 'Social Media', value: 20, color: '#F59E0B' },
      { name: 'Email', value: 12, color: '#EF4444' },
      { name: 'Referral', value: 8, color: '#10B981' },
    ],
    performance: [
      { time: '00:00', accuracy: 91, confidence: 87 },
      { time: '04:00', accuracy: 93, confidence: 89 },
      { time: '08:00', accuracy: 95, confidence: 92 },
      { time: '12:00', accuracy: 94, confidence: 90 },
      { time: '16:00', accuracy: 96, confidence: 94 },
      { time: '20:00', accuracy: 94, confidence: 91 },
    ],
  },
  campaigns: [
    {
      id: 1,
      name: 'Summer Sale Campaign',
      status: 'Active',
      budget: '$5,000',
      spent: '$3,456',
      impressions: '125,432',
      clicks: '4,321',
      conversions: '234',
      ctr: '3.44%',
      cpc: '$0.80',
      date: '2024-01-15',
    },
    {
      id: 2,
      name: 'Brand Awareness Drive',
      status: 'Active',
      budget: '$8,000',
      spent: '$5,234',
      impressions: '234,567',
      clicks: '6,789',
      conversions: '412',
      ctr: '2.89%',
      cpc: '$0.77',
      date: '2024-01-10',
    },
    {
      id: 3,
      name: 'Holiday Special',
      status: 'Completed',
      budget: '$12,000',
      spent: '$11,890',
      impressions: '456,789',
      clicks: '12,345',
      conversions: '876',
      ctr: '2.70%',
      cpc: '$0.96',
      date: '2023-12-01',
    },
  ],
}